# Generated by Django 4.2 on 2025-10-19 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmotionRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200, verbose_name='Аты-жөні')),
                ('age_group', models.CharField(max_length=50, verbose_name='Жас аралығы')),
                ('emotion', models.CharField(max_length=50, verbose_name='Доминант эмоция')),
                ('avg_score', models.FloatField(verbose_name='Орташа индекс')),
                ('advice', models.TextField(verbose_name='Кеңес')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Эмоция жазбасы',
                'verbose_name_plural': 'Эмоция жазбалары',
            },
        ),
        migrations.DeleteModel(
            name='Student',
        ),
    ]
